apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-deployment
spec:
  replicas: 2
  selector:
	matchLabels:
  	app: efs-deployment
  template:
	metadata:
  	labels:
    	app: efs-deployment
	spec:
  	containers:
  	- name: efs-container
    	image: nginx:latest
    	volumeMounts:
    	- name: efs-volume
      	mountPath: /efs
  	volumes:
  	- name: efs-volume
    	persistentVolumeClaim:
      	claimName: efs-pvc

