---
- name: Shutdown Ubuntu instances only
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Shutdown Ubuntu instances
      ansible.builtin.command: /sbin/shutdown -h now
      when: ansible_facts['os_family'] == "Debian"

